name:                Class101
version:             0.1.0.0
github:              "matthiascy/Class101"
license:             Apache-2.0
author:              "Yang CHEN, Pierre Martinet"
maintainer:          "matthias_cy@outlook.com"
copyright:           "Copyright (c) 2018 Yang CHEN, Pierre Martinet"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/matthiascy/Class101#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Class101-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Class101

tests:
  Class101-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Class101
